server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  application:
    name: identity
  datasource:
    url: "jdbc:mysql://localhost:3307/identity_service"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "1E4BEeshlG+55vB4ZdEBscAw4gEW0HqMeva26R8HyUBDr8jLW3XT68wuDONhlzyl"
  valid-duration: 60 # 1 minute
  refreshable-duration: 120 # 2 minutes